version: "3.9"

# Re-use common podman options (mainly SELinux)
x-common-opts: &common-opts
  security_opt:
    - label=disable

volumes:
  kafka-data:
  mysql-data:
  cassandra-data:

networks:
  default:
    name: leaderboard-net
    driver: bridge

services:

  zookeeper:
    <<: *common-opts
    image: docker.io/confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    <<: *common-opts
    image: docker.io/confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Expose one listener for host (localhost) and one for container-to-container traffic
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka-data:/var/lib/kafka/data

  schema-registry:
    <<: *common-opts
    image: docker.io/confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    depends_on:
      - kafka
    restart: unless-stopped
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: INTERNAL://kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
      - "8081:8081"

  mysql:
    <<: *common-opts
    image: docker.io/mysql:8.0
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root            # change for real use
      MYSQL_DATABASE: leaderboard
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  cassandra:
    <<: *common-opts
    image: docker.io/cassandra:4.1
    container_name: cassandra
    restart: unless-stopped
    environment:
      CASSANDRA_CLUSTER_NAME: "GLCluster"
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 256M
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra

  kafka-ui:
    <<: *common-opts
    image: docker.io/provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - "8080:8080"