// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/score_update.proto
// Protobuf Java Version: 4.33.0

package com.example.leaderboard.proto;

@com.google.protobuf.Generated
public interface ScoreUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leaderboard.ScoreUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string leaderboard_id = 1;</code>
   * @return The leaderboardId.
   */
  java.lang.String getLeaderboardId();
  /**
   * <code>string leaderboard_id = 1;</code>
   * @return The bytes for leaderboardId.
   */
  com.google.protobuf.ByteString
      getLeaderboardIdBytes();

  /**
   * <code>string player_id = 2;</code>
   * @return The playerId.
   */
  java.lang.String getPlayerId();
  /**
   * <code>string player_id = 2;</code>
   * @return The bytes for playerId.
   */
  com.google.protobuf.ByteString
      getPlayerIdBytes();

  /**
   * <pre>
   * current score / delta—interpretation left to downstream
   * </pre>
   *
   * <code>int64 score = 3;</code>
   * @return The score.
   */
  long getScore();

  /**
   * <pre>
   * client-supplied epoch-ms
   * </pre>
   *
   * <code>int64 timestamp_ms = 4;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();
}
