// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/score_update.proto
// Protobuf Java Version: 4.33.0

package com.example.leaderboard.proto;

@com.google.protobuf.Generated
public final class ScoreUpdateOuterClass extends com.google.protobuf.GeneratedFile {
  private ScoreUpdateOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "ScoreUpdateOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_leaderboard_ScoreUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leaderboard_ScoreUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/score_update.proto\022\013leaderboard\"" +
      "]\n\013ScoreUpdate\022\026\n\016leaderboard_id\030\001 \001(\t\022\021" +
      "\n\tplayer_id\030\002 \001(\t\022\r\n\005score\030\003 \001(\003\022\024\n\014time" +
      "stamp_ms\030\004 \001(\003B!\n\035com.example.leaderboar" +
      "d.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_leaderboard_ScoreUpdate_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_leaderboard_ScoreUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leaderboard_ScoreUpdate_descriptor,
        new java.lang.String[] { "LeaderboardId", "PlayerId", "Score", "TimestampMs", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
