// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/score_update.proto
// Protobuf Java Version: 4.33.0

package com.example.leaderboard.proto;

/**
 * Protobuf type {@code leaderboard.ScoreUpdate}
 */
@com.google.protobuf.Generated
public final class ScoreUpdate extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:leaderboard.ScoreUpdate)
    ScoreUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "ScoreUpdate");
  }
  // Use ScoreUpdate.newBuilder() to construct.
  private ScoreUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ScoreUpdate() {
    leaderboardId_ = "";
    playerId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.leaderboard.proto.ScoreUpdateOuterClass.internal_static_leaderboard_ScoreUpdate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.leaderboard.proto.ScoreUpdateOuterClass.internal_static_leaderboard_ScoreUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.leaderboard.proto.ScoreUpdate.class, com.example.leaderboard.proto.ScoreUpdate.Builder.class);
  }

  public static final int LEADERBOARD_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object leaderboardId_ = "";
  /**
   * <code>string leaderboard_id = 1;</code>
   * @return The leaderboardId.
   */
  @java.lang.Override
  public java.lang.String getLeaderboardId() {
    java.lang.Object ref = leaderboardId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      leaderboardId_ = s;
      return s;
    }
  }
  /**
   * <code>string leaderboard_id = 1;</code>
   * @return The bytes for leaderboardId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLeaderboardIdBytes() {
    java.lang.Object ref = leaderboardId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      leaderboardId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object playerId_ = "";
  /**
   * <code>string player_id = 2;</code>
   * @return The playerId.
   */
  @java.lang.Override
  public java.lang.String getPlayerId() {
    java.lang.Object ref = playerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playerId_ = s;
      return s;
    }
  }
  /**
   * <code>string player_id = 2;</code>
   * @return The bytes for playerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayerIdBytes() {
    java.lang.Object ref = playerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCORE_FIELD_NUMBER = 3;
  private long score_ = 0L;
  /**
   * <pre>
   * current score / delta—interpretation left to downstream
   * </pre>
   *
   * <code>int64 score = 3;</code>
   * @return The score.
   */
  @java.lang.Override
  public long getScore() {
    return score_;
  }

  public static final int TIMESTAMP_MS_FIELD_NUMBER = 4;
  private long timestampMs_ = 0L;
  /**
   * <pre>
   * client-supplied epoch-ms
   * </pre>
   *
   * <code>int64 timestamp_ms = 4;</code>
   * @return The timestampMs.
   */
  @java.lang.Override
  public long getTimestampMs() {
    return timestampMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(leaderboardId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, leaderboardId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, playerId_);
    }
    if (score_ != 0L) {
      output.writeInt64(3, score_);
    }
    if (timestampMs_ != 0L) {
      output.writeInt64(4, timestampMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(leaderboardId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, leaderboardId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, playerId_);
    }
    if (score_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, score_);
    }
    if (timestampMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, timestampMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.leaderboard.proto.ScoreUpdate)) {
      return super.equals(obj);
    }
    com.example.leaderboard.proto.ScoreUpdate other = (com.example.leaderboard.proto.ScoreUpdate) obj;

    if (!getLeaderboardId()
        .equals(other.getLeaderboardId())) return false;
    if (!getPlayerId()
        .equals(other.getPlayerId())) return false;
    if (getScore()
        != other.getScore()) return false;
    if (getTimestampMs()
        != other.getTimestampMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEADERBOARD_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderboardId().hashCode();
    hash = (37 * hash) + PLAYER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerId().hashCode();
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getScore());
    hash = (37 * hash) + TIMESTAMP_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.leaderboard.proto.ScoreUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.leaderboard.proto.ScoreUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.leaderboard.proto.ScoreUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.leaderboard.proto.ScoreUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.leaderboard.proto.ScoreUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.leaderboard.proto.ScoreUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.leaderboard.proto.ScoreUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.leaderboard.proto.ScoreUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.leaderboard.proto.ScoreUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.leaderboard.proto.ScoreUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.leaderboard.proto.ScoreUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.leaderboard.proto.ScoreUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.leaderboard.proto.ScoreUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code leaderboard.ScoreUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:leaderboard.ScoreUpdate)
      com.example.leaderboard.proto.ScoreUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.leaderboard.proto.ScoreUpdateOuterClass.internal_static_leaderboard_ScoreUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.leaderboard.proto.ScoreUpdateOuterClass.internal_static_leaderboard_ScoreUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.leaderboard.proto.ScoreUpdate.class, com.example.leaderboard.proto.ScoreUpdate.Builder.class);
    }

    // Construct using com.example.leaderboard.proto.ScoreUpdate.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      leaderboardId_ = "";
      playerId_ = "";
      score_ = 0L;
      timestampMs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.leaderboard.proto.ScoreUpdateOuterClass.internal_static_leaderboard_ScoreUpdate_descriptor;
    }

    @java.lang.Override
    public com.example.leaderboard.proto.ScoreUpdate getDefaultInstanceForType() {
      return com.example.leaderboard.proto.ScoreUpdate.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.leaderboard.proto.ScoreUpdate build() {
      com.example.leaderboard.proto.ScoreUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.leaderboard.proto.ScoreUpdate buildPartial() {
      com.example.leaderboard.proto.ScoreUpdate result = new com.example.leaderboard.proto.ScoreUpdate(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.leaderboard.proto.ScoreUpdate result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.leaderboardId_ = leaderboardId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.playerId_ = playerId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.score_ = score_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timestampMs_ = timestampMs_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.leaderboard.proto.ScoreUpdate) {
        return mergeFrom((com.example.leaderboard.proto.ScoreUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.leaderboard.proto.ScoreUpdate other) {
      if (other == com.example.leaderboard.proto.ScoreUpdate.getDefaultInstance()) return this;
      if (!other.getLeaderboardId().isEmpty()) {
        leaderboardId_ = other.leaderboardId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPlayerId().isEmpty()) {
        playerId_ = other.playerId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getScore() != 0L) {
        setScore(other.getScore());
      }
      if (other.getTimestampMs() != 0L) {
        setTimestampMs(other.getTimestampMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              leaderboardId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              playerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              score_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              timestampMs_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object leaderboardId_ = "";
    /**
     * <code>string leaderboard_id = 1;</code>
     * @return The leaderboardId.
     */
    public java.lang.String getLeaderboardId() {
      java.lang.Object ref = leaderboardId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderboardId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string leaderboard_id = 1;</code>
     * @return The bytes for leaderboardId.
     */
    public com.google.protobuf.ByteString
        getLeaderboardIdBytes() {
      java.lang.Object ref = leaderboardId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderboardId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string leaderboard_id = 1;</code>
     * @param value The leaderboardId to set.
     * @return This builder for chaining.
     */
    public Builder setLeaderboardId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      leaderboardId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string leaderboard_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeaderboardId() {
      leaderboardId_ = getDefaultInstance().getLeaderboardId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string leaderboard_id = 1;</code>
     * @param value The bytes for leaderboardId to set.
     * @return This builder for chaining.
     */
    public Builder setLeaderboardIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      leaderboardId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object playerId_ = "";
    /**
     * <code>string player_id = 2;</code>
     * @return The playerId.
     */
    public java.lang.String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string player_id = 2;</code>
     * @return The bytes for playerId.
     */
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string player_id = 2;</code>
     * @param value The playerId to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      playerId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string player_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerId() {
      playerId_ = getDefaultInstance().getPlayerId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string player_id = 2;</code>
     * @param value The bytes for playerId to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      playerId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long score_ ;
    /**
     * <pre>
     * current score / delta—interpretation left to downstream
     * </pre>
     *
     * <code>int64 score = 3;</code>
     * @return The score.
     */
    @java.lang.Override
    public long getScore() {
      return score_;
    }
    /**
     * <pre>
     * current score / delta—interpretation left to downstream
     * </pre>
     *
     * <code>int64 score = 3;</code>
     * @param value The score to set.
     * @return This builder for chaining.
     */
    public Builder setScore(long value) {

      score_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * current score / delta—interpretation left to downstream
     * </pre>
     *
     * <code>int64 score = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearScore() {
      bitField0_ = (bitField0_ & ~0x00000004);
      score_ = 0L;
      onChanged();
      return this;
    }

    private long timestampMs_ ;
    /**
     * <pre>
     * client-supplied epoch-ms
     * </pre>
     *
     * <code>int64 timestamp_ms = 4;</code>
     * @return The timestampMs.
     */
    @java.lang.Override
    public long getTimestampMs() {
      return timestampMs_;
    }
    /**
     * <pre>
     * client-supplied epoch-ms
     * </pre>
     *
     * <code>int64 timestamp_ms = 4;</code>
     * @param value The timestampMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampMs(long value) {

      timestampMs_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * client-supplied epoch-ms
     * </pre>
     *
     * <code>int64 timestamp_ms = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampMs() {
      bitField0_ = (bitField0_ & ~0x00000008);
      timestampMs_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:leaderboard.ScoreUpdate)
  }

  // @@protoc_insertion_point(class_scope:leaderboard.ScoreUpdate)
  private static final com.example.leaderboard.proto.ScoreUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.leaderboard.proto.ScoreUpdate();
  }

  public static com.example.leaderboard.proto.ScoreUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScoreUpdate>
      PARSER = new com.google.protobuf.AbstractParser<ScoreUpdate>() {
    @java.lang.Override
    public ScoreUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ScoreUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScoreUpdate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.leaderboard.proto.ScoreUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

